# Generated by Django 2.2.3 on 2019-07-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_top', models.ImageField(default='default.jpg', upload_to='top_5')),
                ('title', models.CharField(max_length=100)),
                ('old_prais', models.CharField(max_length=100)),
                ('new_prais', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
