# Generated by Django 2.2.3 on 2019-08-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
